/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/auth/admin/invite": {
    /**
     * Generate an invite link for a new user (Admin only)
     * @description Creates a new invite link that can be sent to a user for registration. Only admin users can perform this operation.
     */
    post: operations["generateInviteLink"];
  };
  "/api/auth/invite/validate": {
    /**
     * Validate an invite link token
     * @description Checks if an invite link token is valid, not expired, and has not been used already.
     */
    get: operations["validateInviteLink"];
  };
  "/api/auth/register": {
    /**
     * Register a new user via invite link
     * @description Creates a new user account using a valid invite link. The invite link must be valid and unused. Username must be unique and password must meet security requirements.
     */
    post: operations["registerUser"];
  };
  "/api/auth/login": {
    /**
     * Authenticate user and issue tokens
     * @description Authenticates a user with email and password, returning both an access token and refresh token. Rate limiting is applied to prevent brute force attacks.
     */
    post: operations["login"];
  };
  "/api/auth/token/refresh": {
    /**
     * Refresh access token using refresh token
     * @description Issues a new access token using a valid refresh token. The refresh token must not be expired or revoked.
     */
    post: operations["refreshAccessToken"];
  };
  "/api/auth/admin/password-reset": {
    /**
     * Request a password reset link (Admin generates for user)
     * @description Generates a password reset link for a user. Only admin users can perform this operation. The link is sent to the user for password reset confirmation.
     */
    post: operations["generatePasswordResetLink"];
  };
  "/api/auth/password-reset/confirm": {
    /**
     * Reset password using reset link
     * @description Resets a user's password using a valid password reset token. The token must not be expired or already used.
     */
    post: operations["resetPassword"];
  };
  "/api/health/medication": {
    /**
     * Add a medication administration record
     * @description Records a medication administration event with the date, time, medication name, and dosage. Requires authentication.
     */
    post: operations["createMedicationRecord"];
  };
  "/api/health/bottle": {
    /**
     * Add a bottle/hydration consumption record
     * @description Records a hydration event including the date, time, and quantity consumed. Helps track daily fluid intake. Requires authentication.
     */
    post: operations["createBottleRecord"];
  };
  "/api/health/bowel-movement": {
    /**
     * Add a bowel movement record
     * @description Records a bowel movement event with the date, time, and consistency level (Hard, Normal, Soft, or Diarrhea). Requires authentication.
     */
    post: operations["createBowelMovementRecord"];
  };
  "/api/health/solid-food": {
    /**
     * Add a solid food consumption record
     * @description Records solid food consumption with the date, time, food description, and quantity. Tracks dietary intake. Requires authentication.
     */
    post: operations["createSolidFoodRecord"];
  };
  "/api/health/note": {
    /**
     * Add a note/observation record
     * @description Records a general note or observation with the date, time, notes content, and optional category. Allows free-form health tracking. Requires authentication.
     */
    post: operations["createNoteRecord"];
  };
  "/api/health/summary/{date}": {
    /**
     * Retrieve daily summary for a given date
     * @description Retrieves all health records for a specific date, organized by record type (medications, hydration, bowel movements, food, observations). Requires authentication.
     */
    get: operations["getSummaryByDate"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    GenerateInviteRequest: {
      /**
       * Format: email
       * @description Email address for the invite
       */
      email: string;
    };
    GenerateInviteResponse: {
      /** Format: uuid */
      id?: string;
      /** @description Unique invite token */
      token?: string;
      /** Format: email */
      email?: string;
      /** Format: date-time */
      expiresAt?: string;
      message?: string;
    };
    RegisterRequest: {
      /** @description Unique invite token */
      inviteToken: string;
      /**
       * Format: email
       * @description User email address
       */
      email: string;
      /** @description Unique username */
      username: string;
      /** @description User's full name */
      name: string;
      /** @description Password (min 8 characters) */
      password: string;
    };
    RegisterResponse: {
      /** Format: uuid */
      id?: string;
      email?: string;
      message?: string;
    };
    LoginRequest: {
      /**
       * Format: email
       * @description User email address
       */
      email: string;
      /** @description User password */
      password: string;
    };
    LoginResponse: {
      /** @description JWT access token */
      accessToken?: string;
      /** Format: date-time */
      accessTokenExpiresAt?: string;
      /** @description JWT refresh token */
      refreshToken?: string;
      /** Format: date-time */
      refreshTokenExpiresAt?: string;
      message?: string;
    };
    RefreshTokenRequest: {
      /** @description Refresh token */
      refreshToken: string;
    };
    RefreshTokenResponse: {
      /** @description New JWT access token */
      accessToken?: string;
      /** Format: date-time */
      expiresAt?: string;
      message?: string;
    };
    PasswordResetLinkResponse: {
      /** @description Reset token */
      token?: string;
      /** Format: date-time */
      expiresAt?: string;
      message?: string;
    };
    ResetPasswordRequest: {
      /** @description Password reset token */
      resetToken: string;
      /** @description New password (min 8 characters) */
      newPassword: string;
    };
    MedicationAdministration: {
      /**
       * Format: date
       * @description Date of medication
       */
      date: string;
      /**
       * Format: time
       * @description Time of medication administration
       */
      time: string;
      /** @description Name of medication */
      medication?: string;
      /** @description Dosage amount */
      dosage?: string;
    };
    BottleConsumption: {
      /**
       * Format: date
       * @description Date of consumption
       */
      date: string;
      /**
       * Format: time
       * @description Time of consumption
       */
      time: string;
      /** @description Amount consumed in ml or oz */
      quantity?: number;
    };
    BowelMovement: {
      /**
       * Format: date
       * @description Date of bowel movement
       */
      date: string;
      /**
       * Format: time
       * @description Time of bowel movement
       */
      time: string;
      /**
       * @description Consistency of bowel movement
       * @enum {string}
       */
      consistency?: "Hard" | "Normal" | "Soft" | "Diarrhea";
    };
    SolidFoodConsumption: {
      /**
       * Format: date
       * @description Date of food consumption
       */
      date: string;
      /**
       * Format: time
       * @description Time of food consumption
       */
      time: string;
      /** @description Description of food consumed */
      food?: string;
      /** @description Amount consumed */
      quantity?: string;
    };
    Observation: {
      /**
       * Format: date
       * @description Date of observation
       */
      date: string;
      /**
       * Format: time
       * @description Time of observation
       */
      time: string;
      /** @description Observation notes/text */
      notes?: string;
      /** @description Category of observation */
      category?: string;
    };
    DailySummary: {
      /** Format: date */
      date?: string;
      data?: components["schemas"]["HealthRecord"][];
    };
    HealthRecord: {
      /** Format: uuid */
      id?: string;
      /** Format: date */
      date?: string;
      /** Format: time */
      time?: string;
      recordType?: string;
      summary?: string;
    };
    Error: {
      statusCode?: number;
      message: string;
      details?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /**
   * Generate an invite link for a new user (Admin only)
   * @description Creates a new invite link that can be sent to a user for registration. Only admin users can perform this operation.
   */
  generateInviteLink: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["GenerateInviteRequest"];
      };
    };
    responses: {
      /** @description Invite link successfully generated */
      201: {
        content: {
          "application/json": components["schemas"]["GenerateInviteResponse"];
        };
      };
      /** @description Unauthorized - Admin access required */
      401: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /**
   * Validate an invite link token
   * @description Checks if an invite link token is valid, not expired, and has not been used already.
   */
  validateInviteLink: {
    parameters: {
      query: {
        /** @description Invite token to validate */
        token: string;
      };
    };
    responses: {
      /** @description Invite link is valid */
      200: {
        content: {
          "application/json": {
            message?: string;
          };
        };
      };
      /** @description Invalid or expired invite link */
      400: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /**
   * Register a new user via invite link
   * @description Creates a new user account using a valid invite link. The invite link must be valid and unused. Username must be unique and password must meet security requirements.
   */
  registerUser: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["RegisterRequest"];
      };
    };
    responses: {
      /** @description User successfully registered */
      201: {
        content: {
          "application/json": components["schemas"]["RegisterResponse"];
        };
      };
      /** @description Invalid request or validation failed */
      400: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /**
   * Authenticate user and issue tokens
   * @description Authenticates a user with email and password, returning both an access token and refresh token. Rate limiting is applied to prevent brute force attacks.
   */
  login: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"];
      };
    };
    responses: {
      /** @description Successfully authenticated */
      200: {
        content: {
          "application/json": components["schemas"]["LoginResponse"];
        };
      };
      /** @description Invalid credentials or rate limit exceeded */
      401: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /**
   * Refresh access token using refresh token
   * @description Issues a new access token using a valid refresh token. The refresh token must not be expired or revoked.
   */
  refreshAccessToken: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["RefreshTokenRequest"];
      };
    };
    responses: {
      /** @description New access token issued */
      200: {
        content: {
          "application/json": components["schemas"]["RefreshTokenResponse"];
        };
      };
      /** @description Invalid or expired refresh token */
      401: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /**
   * Request a password reset link (Admin generates for user)
   * @description Generates a password reset link for a user. Only admin users can perform this operation. The link is sent to the user for password reset confirmation.
   */
  generatePasswordResetLink: {
    parameters: {
      query: {
        /** @description ID of user requesting password reset */
        userId: string;
      };
    };
    responses: {
      /** @description Password reset link generated */
      200: {
        content: {
          "application/json": components["schemas"]["PasswordResetLinkResponse"];
        };
      };
      /** @description Forbidden - Admin access required */
      403: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /**
   * Reset password using reset link
   * @description Resets a user's password using a valid password reset token. The token must not be expired or already used.
   */
  resetPassword: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ResetPasswordRequest"];
      };
    };
    responses: {
      /** @description Password successfully reset */
      200: {
        content: {
          "application/json": {
            message?: string;
          };
        };
      };
      /** @description Invalid reset token or password validation failed */
      400: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /**
   * Add a medication administration record
   * @description Records a medication administration event with the date, time, medication name, and dosage. Requires authentication.
   */
  createMedicationRecord: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["MedicationAdministration"];
      };
    };
    responses: {
      /** @description Medication record created successfully */
      201: {
        content: {
          "application/json": {
            /** Format: uuid */
            id?: string;
            message?: string;
          };
        };
      };
      /** @description Date and Time are required */
      400: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Unauthorized - Valid access token required */
      401: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Conflict - Record could not be created */
      409: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /**
   * Add a bottle/hydration consumption record
   * @description Records a hydration event including the date, time, and quantity consumed. Helps track daily fluid intake. Requires authentication.
   */
  createBottleRecord: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["BottleConsumption"];
      };
    };
    responses: {
      /** @description Bottle record created successfully */
      201: {
        content: {
          "application/json": {
            /** Format: uuid */
            id?: string;
            message?: string;
          };
        };
      };
      /** @description Date and Time are required */
      400: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Unauthorized - Valid access token required */
      401: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Conflict - Record could not be created */
      409: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /**
   * Add a bowel movement record
   * @description Records a bowel movement event with the date, time, and consistency level (Hard, Normal, Soft, or Diarrhea). Requires authentication.
   */
  createBowelMovementRecord: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["BowelMovement"];
      };
    };
    responses: {
      /** @description Bowel movement record created successfully */
      201: {
        content: {
          "application/json": {
            /** Format: uuid */
            id?: string;
            message?: string;
          };
        };
      };
      /** @description Date and Time are required */
      400: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Unauthorized - Valid access token required */
      401: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Conflict - Record could not be created */
      409: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /**
   * Add a solid food consumption record
   * @description Records solid food consumption with the date, time, food description, and quantity. Tracks dietary intake. Requires authentication.
   */
  createSolidFoodRecord: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["SolidFoodConsumption"];
      };
    };
    responses: {
      /** @description Solid food record created successfully */
      201: {
        content: {
          "application/json": {
            /** Format: uuid */
            id?: string;
            message?: string;
          };
        };
      };
      /** @description Date and Time are required */
      400: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Unauthorized - Valid access token required */
      401: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Conflict - Record could not be created */
      409: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /**
   * Add a note/observation record
   * @description Records a general note or observation with the date, time, notes content, and optional category. Allows free-form health tracking. Requires authentication.
   */
  createNoteRecord: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["Observation"];
      };
    };
    responses: {
      /** @description Note record created successfully */
      201: {
        content: {
          "application/json": {
            /** Format: uuid */
            id?: string;
            message?: string;
          };
        };
      };
      /** @description Date and Time are required */
      400: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Unauthorized - Valid access token required */
      401: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Conflict - Record could not be created */
      409: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /**
   * Retrieve daily summary for a given date
   * @description Retrieves all health records for a specific date, organized by record type (medications, hydration, bowel movements, food, observations). Requires authentication.
   */
  getSummaryByDate: {
    parameters: {
      path: {
        /** @description Date in yyyy-MM-dd format */
        date: string;
      };
    };
    responses: {
      /** @description Daily summary retrieved successfully */
      200: {
        content: {
          "application/json": components["schemas"]["DailySummary"];
        };
      };
      /** @description Invalid date format */
      400: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Unauthorized - Valid access token required */
      401: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
}
